/*
    dx_form_creator/blob/develop/src/js/admin/setting.js#L240
    に記載があるがpageというプロパティがない？
    Serializer.removeProperty('question', 'page');
*/

/*
      プロパティ追加は以下参考
      Serializer.addProperty('question', {
      name: 'cost:number',
      category: 'general',
      default: 5,
      minValue: 0,
      maxValue: 100,
      });
  */

const propertyBlackList = [
  // "name",
  'state',
  // "visible",
  'useDisplayValuesInTitle',
  // "visibleIf",
  'width',
  'minWidth',
  'maxWidth',
  // "startWithNewLine",
  'indent',
  // "title",
  // "titleLocation",
  // "description",
  'descriptionLocation',
  'hideNumber',
  'valueName',
  // "enableIf",
  // "defaultValue",
  // "defaultValueExpression",
  'correctAnswer',
  // "isRequired",
  // "requiredIf",
  // "requiredErrorText",
  'readOnly',
  // "validators",
  'bindings',
  // "inputType",
  'size',
  'textUpdateMode',
  'autoComplete',
  'min',
  'max',
  'minValueExpression',
  'maxValueExpression',
  'minErrorText',
  'maxErrorText',
  'step',
  // "minLength"
  // "maxLength",
  // "placeHolder",
  'dataList',
  'hasComment',
  'commentText',
  'choicesFromQuestion',
  // "choices",
  'choicesFromQuestionMode',
  'choicesOrder',
  'choicesByUrl',
  'hideIfChoicesEmpty',
  'choicesVisibleIf',
  'choicesEnableIf',
  'choicesMin',
  'choicesMax',
  'choicesStep',
  // "hasOther",
  'otherPlaceHolder',
  'otherText',
  'otherErrorText',
  'colCount',
  'hasSelectAll',
  'hasNone',
  'maxSelectedChoices',
  'noneText',
  'selectAllText',
  'showClearButton',
  'showPreview',
  'allowMultiple',
  'allowImagesPreview',
  'imageHeight',
  'imageWidth',
  // "acceptedTypes",
  'storeDataAsText',
  'waitForUpload',
  // "maxSize",
  'needConfirmRemoveFile',
  // "items",
  'itemSize',
  // "rateValues",
  // "rateMin",
  // "rateMax",
  'rateStep',
  // "minRateDescription",
  // "maxRateDescription",
  'cols',
  'rows',
  'locale',
  'logo',
  'showTimerPanelMode',
  'logoWidth',
  'logoHeight',
  'logoFit',
  'logoPosition',
  'focusFirstQuestionAutomatic',
  'focusOnFirstError',
  // "completedHtml",
  'completedBeforeHtml',
  'completedHtmlOnCondition',
  'loadingHtml',
  'pages',
  'triggers',
  'calculatedValues',
  'cookieName',
  'sendResultOnPageNext',
  'showNavigationButtons',
  'showPrevButton',
  'showTitle',
  'showPageTitles',
  'showCompletedPage',
  // "navigateToUrl",
  'navigateToUrlOnCondition',
  'questionsOrder',
  'showPageNumbers',
  'showQuestionNumbers',
  'questionTitleLocation',
  'questionDescriptionLocation',
  'questionErrorLocation',
  'showProgressBar',
  'progressBarType',
  'mode',
  'storeOthersAsComment',
  'maxTextLength',
  'maxOthersLength',
  'goNextPageAutomatic',
  'clearInvisibleValues',
  'checkErrorsMode',
  'startSurveyText',
  'pagePrevText',
  'pageNextText',
  'completeText',
  'previewText',
  'editText',
  // "requiredText",
  'questionStartIndex',
  'questionTitlePattern',
  'firstPageIsStarted',
  'questionsOnPageMode',
  // "showPreviewBeforeComplete",
  'maxTimeToFinish',
  'maxTimeToFinishPage',
  'showTimerPanel',
  'navigationButtonsVisibility',
  'visible',
  'autoGrow',
  'multiLine',
  'autoGrowComment',
  'widthMode',
  // "send"
];

export const visibledProperties = (creator) =>
  creator.onShowingProperty.add(function (sender, options) {
    options.canShow = propertyBlackList.indexOf(options.property.name) == -1;
  });
